# Site settings
author: Jessi Ortega
title: Hypebeast
header-img: img/home-bg.png
email: ortegabx05@gmail.com
copyright_name: Jessi Ortega
description: > # this means to ignore newlines until "baseurl:"
  From Sneakers to Coding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ortegabx05

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
